spring:
    application:
        name: Diplr
    messages:
        basename: i18n/messages
    thymeleaf:
        mode: XHTML
    http:
      multipart:
        location: /tmp
        max-file-size: 150MB
        max-request-size: 200MB
server:
    port: 8080
    session:
        cookie:
            http-only: true
debug: true
#logging
logging:
  level:
    org:
      springframework: INFO
    com:
      diplr: DEBUG

